### ISSUE TITLE
Route "entity.log_type.edit_form" does not exist.

### ISSUE THREAD

**Issue by mstenta** [zaporylie/log#19]
The log type edit route is not defined. It looks like it was removed in this commit: https://github.com/zaporylie/log/commit/fd83f02e4565a8b17196feb9a221c96b8da4bc04

Steps to reproduce:
1. Install Log module.
2. Go to /admin/structure/logs
3. Click "Add Log type"
4. Enter "test" in all fields"
5. Click "Save"
6. Error displays: "The website encountered an unexpected error. Please try again later."

In the log:

```
Uncaught PHP Exception Symfony\\Component\\Routing\\Exception\\RouteNotFoundException: "Route "entity.log_type.edit_form" does not exist." at /var/aegir/platforms/drupal/8.1.1/core/lib/Drupal/Core/Routing/RouteProvider.php line 186, referer: http://8x.local/admin/structure/logs/add
```

**Comment by zaporylie** [comment]
Pull request #21
